wandb_version: 1

policy_type:
  desc: null
  value: MultiInputPolicy
total_timesteps:
  desc: null
  value: 10000
env_name:
  desc: null
  value: ScmIrl-v0
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716024253
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 22
      - 23
      - 35
      4: 3.11.8
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.MultiInputActorCriticPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 10000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1716024263078636420
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "OrderedDict([('agent_state', array([[1.9443076e+03, 2.6186636e+03, 4.9900680e+00,\
    \ 3.9192337e-01]],\n      dtype=float32)), ('observation_matrix', array([[[50.,\
    \ 50., 50., ..., 50., 50., 50.],\n        [50., 50., 50., ..., 50., 50., 50.],\n\
    \        [50., 50., 50., ..., 50., 50., 50.],\n        ...,\n        [50., 50.,\
    \ 50., ..., 50., 50., 50.],\n        [50., 50., 50., ..., 50., 50., 50.],\n  \
    \      [50., 50., 50., ..., 50., 50., 50.]]], dtype=float32)), ('target', array([[6221.385,\
    \ 6272.325]], dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x76170274e250>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''agent_state'': Box(-inf, inf, (4,), float32), ''observation_matrix'':
    Box(-100.0, 100.0, (400, 700), float32), ''target'': Box(-inf, inf, (2,), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (2,), float32)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.DictRolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7617027e19e0>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7617027e2660>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.DictRolloutBuffer object at 0x761704b583d0>
policy:
  desc: null
  value: "MultiInputActorCriticPolicy(\n  (features_extractor): CombinedExtractor(\n\
    \    (extractors): ModuleDict(\n      (agent_state): Flatten(start_dim=1, end_dim=-1)\n\
    \      (observation_matrix): Flatten(start_dim=1, end_dim=-1)\n      (target):\
    \ Flatten(start_dim=1, end_dim=-1)\n    )\n  )\n  (pi_features_extractor): CombinedExtractor(\n\
    \    (extractors): ModuleDict(\n      (agent_state): Flatten(start_dim=1, end_dim=-1)\n\
    \      (observation_matrix): Flatten(start_dim=1, end_dim=-1)\n      (target):\
    \ Flatten(start_dim=1, end_dim=-1)\n    )\n  )\n  (vf_features_extractor): CombinedExtractor(\n\
    \    (extractors): ModuleDict(\n      (agent_state): Flatten(start_dim=1, end_dim=-1)\n\
    \      (observation_matrix): Flatten(start_dim=1, end_dim=-1)\n      (target):\
    \ Flatten(start_dim=1, end_dim=-1)\n    )\n  )\n  (mlp_extractor): MlpExtractor(\n\
    \    (policy_net): Sequential(\n      (0): Linear(in_features=280006, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0):\
    \ Linear(in_features=280006, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=2, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7616a5f13fd0>
