model: 'scm_irl'

irl_algo: 'gail'
lerner_algo: 'ppo'

defaults:
  - env/scenario
  - env/env_cfg
  - shiptypes/tanker

policy: 'MlpPolicy' #MultiInputPolicy
env_name: 'ScmIrl-v0'

# multi scenario
multi_scenario: true
scenarios_path: "../data/raw/"
scenario_id: "113851c356" # In case multi_scenario: False
mmsi: 100 # In case a single scenario is used and unique mmsi
num_envs: 2

# override env parameters
env_params:
  copy_expert: true
  start_time_random: false
  observation_matrix: false

# irl parameters
irl_params:
  min_expert_demos: 2
  demo_batch_size: 64
  total_timesteps: 400_000
  learner_batch_size: 64
  learner_lr: 0.0004



# add nodes from ./env/nodes.yaml
