model: 'scm_irl'


irl_algo: 'gail'
lerner_algo: 'ppo'

defaults:
  - env/scenario
  - env/env_cfg
  - shiptypes/tanker

output_dir: './outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/model'

policy: 'MlpPolicy' #MultiInputPolicy
env_name: 'ScmIrl-v0'

# multi scenario
multi_scenario: true
scenarios_path: "../data/raw/"
scenario_id: "113851c356" # In case multi_scenario: False
mmsi: 100 # In case a single scenario is used and unique mmsi
num_envs: 60


# override env parameters
# env_params:
#   copy_expert: true
#   start_time_random: false
#   observation_matrix: false

resnet_wrapper: true

# irl parameters
irl_params:
  min_expert_demos: 60
  num_eval_episodes: 50
  demo_batch_size: 4096
  total_timesteps: 4_000_000
  num_checkpoints: 10 # save model total_timesteps/num_checkpoints times
  learner_batch_size: 64
  learner_lr: 0.0004

