defaults:
  - env/scenario
  - env/env_cfg
  - shiptypes/tanker

policy: 'MlpPolicy' #MultiInputPolicy
total_timesteps: 500000
env_name: 'ScmIrl-v0'

# multi scenario
multi_scenario: true
scenarios_path: "../data/raw/"
scenario_id: "113851c356" # In case multi_scenario: False
mmsi: 100 # In case a single scenario is used and unique mmsi
num_envs: 1

# override env parameters
env_params:
  copy_expert: true
  start_time_random: true


