defaults:
  - env/scenario
  - env/env_cfg
  - shiptypes/tanker

policy: 'MlpPolicy' #MultiInputPolicy
total_timesteps: 500000
env_name: 'ScmIrl-v0'

# multi scenario
multi_scenario: true
scenarios_path: "../data/raw/"
scenario_name: "scenario_2a66ceaf61" # In case multi_scenario: False
number_envs: 5



# add nodes from ./env/nodes.yaml
